In [200]:
import numpy as np
import pandas as pd

In [201]:
df = pd.read_csv("C:\\Users\\libin_urv2w13\\Desktop\\mljourney\\Supervised-ML\\multiple-Linear-Reg\\car-process\\Car.csv.xls")

In [202]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [203]:
df[df.duplicated()]

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
25,Honda Civic ZX Diesel BSIV,2020,2125000,5500,Diesel,Dealer,Manual,First Owner,26.8 kmpl,1597 CC,118 bhp,300Nm@ 2000rpm,5.0
35,Hyundai Xcent 1.2 VTVT SX,2020,524000,32000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
37,Kia Seltos HTX Plus AT D,2020,1900000,5000,Diesel,Dealer,Automatic,First Owner,17.8 kmpl,1493 CC,113.4 bhp,250nm@ 1500-2750rpm,5.0
44,Maruti Alto 800 LXI,2020,350000,5000,Petrol,Individual,Manual,First Owner,22.05 kmpl,796 CC,47.3 bhp,69Nm@ 3500rpm,5.0
63,Maruti Ignis Zeta AMT,2020,600000,5000,Petrol,Individual,Automatic,First Owner,20.89 kmpl,1197 CC,81.80 bhp,113Nm@ 4200rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8056,Maruti Esteem Lxi,2002,95000,90000,Petrol,Individual,Manual,Third Owner,NaN,NaN,NaN,NaN,NaN
8070,Hyundai Santro GS zipPlus,2001,60000,71000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN
8090,Maruti Alto LX,2000,45957,90000,Petrol,Individual,Manual,Second Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0
8097,Toyota Qualis Fleet A3,2000,200000,100000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN
8114,Mitsubishi Lancer 2.0 GLd,1999,150000,198000,Diesel,Individual,Manual,Second Owner,14.8 kmpl,1998 CC,68 bhp,"12.5@ 3,000(kgm@ rpm)",5.0

In [204]:
df.drop_duplicates(inplace=True)

In [205]:
df[df.duplicated()]

Empty DataFrame
Columns: [Name, year, selling_price, km_driven, fuel, seller_type, transmission, owner, mileage, engine, max_power, torque, seats]
Index: []

In [206]:
df.dtypes

Name              object
year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage           object
engine            object
max_power         object
torque            object
seats            float64
dtype: object

In [207]:
df["brand"] = df["Name"].str.strip().str.split(" ").str[0]
print(df["brand"])
df.drop(columns="Name",inplace=True)

0           Maruti
1            Skoda
2              BMW
3               MG
4             Tata
           ...
8143    Ambassador
8144      Mahindra
8145        Maruti
8146        Maruti
8147      Mahindra
Name: brand, Length: 6946, dtype: object

In [208]:
df["mileage"] = df["mileage"].str.split(" ").str[0]
df["mileage"] = df["mileage"].astype(float)
print(df["mileage"].dtype)
print(df["mileage"])
print(df["mileage"].isnull().sum())

float64
0       19.03
1       14.08
2       18.15
3       32.52
4       12.15
        ...
8143    12.80
8144      NaN
8145    16.10
8146      NaN
8147      NaN
Name: mileage, Length: 6946, dtype: float64
208

In [209]:
df["engine"] = df["engine"].str.split("C").str[0]
df["engine"] = df["engine"].astype(float)
df["engine"]

0        999.0
1       1956.0
2        998.0
3        998.0
4       1451.0
         ...
8143    1995.0
8144       NaN
8145     796.0
8146       NaN
8147       NaN
Name: engine, Length: 6946, dtype: float64

In [210]:
df["max_power"] = df["max_power"].str.split("b").str[0].str.strip()
df[df["max_power"] == ""]
df["max_power"] = df["max_power"].replace("",np.nan)
df["max_power"] = df["max_power"].astype(float)

In [211]:
df["torque"] = df["torque"].str.split("N|n|@|k|\(|K|/").str[0]
df["torque"] = df["torque"].astype(float)
df["torque"].dtype

<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
C:\Users\libin_urv2w13\AppData\Local\Temp\ipykernel_18860\1621809539.py:1: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  df["torque"] = df["torque"].str.split("N|n|@|k|\(|K|/").str[0]

dtype('float64')

In [212]:
df.dtypes

year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine           float64
max_power        float64
torque           float64
seats            float64
brand             object
dtype: object

In [213]:
df.isnull().sum()

year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          208
engine           208
max_power        206
torque           209
seats            208
brand              0
dtype: int64

In [214]:
df.columns[7:12]

Index(['mileage', 'engine', 'max_power', 'torque', 'seats'], dtype='object')

In [215]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df.iloc[:,7:12] = imputer.fit_transform(df.iloc[:,7:12])

In [216]:
df.isnull().sum()

year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
brand            0
dtype: int64

In [217]:
x = df.iloc[:,:]
x.drop(columns="selling_price",inplace=True)
x.head()

,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,brand
0,2023,10000,Petrol,Individual,Manual,First Owner,19.03,999.0,71.01,96.0,5.0,Maruti
1,2023,10000,Petrol,Individual,Manual,First Owner,14.08,1956.0,167.67,350.0,5.0,Skoda
2,2023,1000,Diesel,Dealer,Automatic,First Owner,18.15,998.0,118.35,172.0,5.0,BMW
3,2023,10000,Electric,Dealer,Automatic,First Owner,32.52,998.0,58.33,78.0,5.0,MG
4,2023,10000,Petrol,Individual,Manual,First Owner,12.15,1451.0,141.00,250.0,5.0,Tata

In [218]:
y = df.iloc[:,1]
y

0        410000
1       1350000
2       5800000
3       2650000
4        715000
         ...
8143      99000
8144     120000
8145      45000
8146      55000
8147     300000
Name: selling_price, Length: 6946, dtype: int64

In [219]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("encoder",OneHotEncoder(sparse_output=False),["brand","fuel","seller_type","transmission","owner"])],remainder="passthrough")
x = pd.DataFrame(ct.fit_transform(x),columns=ct.get_feature_names_out())
x

,encoder__brand_Ambassador,encoder__brand_Ashok,encoder__brand_Audi,encoder__brand_BMW,encoder__brand_Chevrolet,encoder__brand_Daewoo,encoder__brand_Datsun,encoder__brand_Fiat,encoder__brand_Force,encoder__brand_Ford,...,encoder__owner_Second Owner,encoder__owner_Test Drive Car,encoder__owner_Third Owner,remainder__year,remainder__km_driven,remainder__mileage,remainder__engine,remainder__max_power,remainder__torque,remainder__seats
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,19.03,999.0,71.01,96.0,5.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,14.08,1956.0,167.67,350.0,5.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,1000.0,18.15,998.0,118.35,172.0,5.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,32.52,998.0,58.33,78.0,5.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,12.15,1451.0,141.00,250.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6941,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1994.0,100000.0,12.80,1995.0,52.00,106.0,5.0
6942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1994.0,100000.0,18.90,1248.0,74.00,200.0,5.0
6943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1994.0,60000.0,16.10,796.0,37.00,59.0,4.0
6944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1991.0,120000.0,18.90,1248.0,74.00,200.0,5.0
6945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1983.0,10000.0,18.90,1248.0,74.00,200.0,5.0

In [220]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=4)

In [221]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [222]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred)*100)

73.34758504855743